### PR TITLE
spake2 code reorganization

### PR DESCRIPTION
**Pull request by newpavlov**
I've moved some tests to `tests` folder and others to `tests.rs`. Also code from `spake2.rs` is moved to `lib.rs`.

### CODE REVIEW

**Comment by newpavlov** [comment]
BTW I think it could be worth to allow failure of the rustfmt pass.

**Comment by warner** [comment]
hrm.. I've had folks encourage me to be strict about rustfmt, to keep things tidy, but I have to admit that it's annoying when 80% of submitted PRs fail because of something that's easy enough for us to fix afterwards.

Yeah, let's make that optional, but we'll need to make it a point to re-check rustfmt frequently, and also to make sure the tree is rustfmt-clean before we start making functional changes, so that commits don't have unrelated changes included in them.

**Comment by warner** [comment]
Oh, I noticed the `#![cfg_attr(test, deny(warnings))]` that was in lib.rs went away.. should we include that in the new `tests.rs` ?

**Comment by warner** [comment]
great, looks good to me

**Comment by newpavlov** [comment]
I've added `#![deny(warnings)]` to the crate. (I probably should do it for other crates as well)

**Comment by newpavlov** [comment]
BTW if you'll have time it would be nice if you'll add crate level docs with a basic description of SPAKE2 and usage example(s).

**Pull request merged**
