### PR TITLE
Bump digest, sha-1, and sha2 dependencies to v0.9

### LINKED ISSUE #20: SRP: 'M' computation does not match RFC5054/RFC2945
RFC5054 refers to RFC2945 for the computation of the 'M' value. However, this implementation does not seem to be following the standard.

'M' should be computed as: M = H(H(N) XOR H(g) | H(U) | s | A | B | K)

But instead, it is computed as: M1 = H(A, B, K)
https://github.com/RustCrypto/PAKEs/blob/master/srp/src/client.rs#L170
https://github.com/RustCrypto/PAKEs/blob/master/srp/src/server.rs#L132

I am not an expert of SRP, but am I missing something? The samples on the wikipedia page match the RFC, but I can't figure out why this implementation differs in that regard.

Thanks for clarifying this portion of the code!

### PR DESCRIPTION
**Pull request by masihyeganeh**
Fixes #20 and #34

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]

**Comment by masihyeganeh** [comment]
@tarcieri 
Sorry for the mess in previous PR.
Please consider merging this one.

**Comment by tarcieri** [comment]
@masihyeganeh no worries. Looks good now, and the tests pass. Thanks!

**Comment by masihyeganeh** [comment]
Thanks for merging. Please let me know when this is available in crates.io

**Comment by tarcieri** [comment]
@masihyeganeh released as v0.5.0 in #38

**Pull request merged**
