### PR TITLE
Add spake2

### PR DESCRIPTION
**Pull request by warner**
This does a "git subtree add", moving the entire history of https://github.com/warner/spake2.rs into the `spake2/` subdirectory of this repo. I *think* that's the appropriate thing to do.. it makes the history look a little funky (there are now two unparented commits, not just the usual one original commit), but it keeps all the revision IDs identical.

If this seems reasonable and we land it, I'll add tags next (with names like spake2-0.1.0), and then update the travis config, then the READMEs.

### CODE REVIEW

**Comment by newpavlov** [comment]
Argh, I've squashed and merged this PR. Do you think I should revert and merge it instead? Maybe it's worth to archive `warner/spake2.rs`. (considering that already published versions point to it)

**Comment by warner** [comment]
Yeah, if you don't mind reverting it, it might be nice to include the history in the repo going forward. Especially the release tags.

If you don't feel comfortable with a force-push, you could revert just the last commit (leaving both forward and backwards commits in the history, but restoring the tree contents to those from the srp-v0.2.5 tag (1afa40d)). Then I can re-run the `git subtree add` and file a new PR.

**Comment by newpavlov** [comment]
Currently it's `spake2-v0.1.0`. Previously I was using `crate_x.y.z`, but plane to rename them one day.

**Comment by warner** [comment]
ok, tags pushed. I'll look at travis and file a PR later.

**Comment by newpavlov** [comment]
I've update readme a bit. BTW how about re-licensing `spake2` under dual `MIT OR Apache-2.0` license for uniformity?

**Comment by warner** [comment]
Done. The badges won't get updated until we push a new release and crates.io sees the change. I fixed the srp/Cargo.toml to point at the correct repo to (PAKEs instead of PAKE).

I'll try to push a new release tonight or tomorrow.

**Pull request merged**
