### PR TITLE
Bump `digest`, `sha-1`, and `sha2` dependencies to v0.9

### LINKED ISSUE #20: SRP: 'M' computation does not match RFC5054/RFC2945
RFC5054 refers to RFC2945 for the computation of the 'M' value. However, this implementation does not seem to be following the standard.

'M' should be computed as: M = H(H(N) XOR H(g) | H(U) | s | A | B | K)

But instead, it is computed as: M1 = H(A, B, K)
https://github.com/RustCrypto/PAKEs/blob/master/srp/src/client.rs#L170
https://github.com/RustCrypto/PAKEs/blob/master/srp/src/server.rs#L132

I am not an expert of SRP, but am I missing something? The samples on the wikipedia page match the RFC, but I can't figure out why this implementation differs in that regard.

Thanks for clarifying this portion of the code!

### PR DESCRIPTION
**Pull request by masihyeganeh**
Fixes #20 and #34

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]
These changes look good to me.

@masihyeganeh the CI failure is due to an MSRV bump to 1.41. Can you update .travis.yml?

(separately we should migrate this repo to GitHub Actions like the rest of the repos)

**Comment by masihyeganeh** [comment]
@tarcieri I'm not sure how to do it.
There is no such thing in .travis.yml
Let me know how and I'll do it fast.

For anyone waiting for this PR to merge, you can use my fork for now, and switch back to main repo when it is merged:
```toml
srp = { git = "https://github.com/masihyeganeh/PAKEs", branch = "patch-2" }
```

**Comment by tarcieri** [comment]
@masihyeganeh I made a PR to bump MSRV: #36 

After I merge that, if you rebase CI should pass

**Comment by masihyeganeh** [comment]
I think I f'ed it up! :|

**Comment by tarcieri** [comment]
@masihyeganeh try:

```
$ git checkout patch-2
$ git reset --hard  84877d0
$ git rebase master
$ git push -f
```

**Pull request closed without merging**
